on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  populate:
    runs-on: ubuntu-latest
    name: Populate GitHub Stars API with blog and YouTube latest posts.
    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Populate
        run: node index.js
